from .benefits_block import generate_benefits_copy
from .usage_block import generate_usage_copy
from .safety_block import generate_safety_copy
from .ingredients_block import generate_ingredients_copy
from .comparison_block import generate_comparison
